### PR TITLE
upgrade deps

### PR DESCRIPTION
**Pull request by goxiaoy**
this pr is blocked by https://github.com/Innim/dart-lint/pull/2

### CODE REVIEW

**Review by stevenmetzger — APPROVED** [review]
Thanks for fixing this. How do we get these changes submitted?

**Comment by goxiaoy** [comment]
> How do we get these changes submitted?

Not sure about what submit means.

I have updated lock file and passed the tests.
You can merge this pr and I see there is a publish workflow, it may trigger a publish action to the pub.dev

**Comment by stevenmetzger** [comment]
Sorry, I meant that I don't have write access to this repository so I can't merge the pull request. Could somebody with write access please do this? Thanks!

**Comment by greymag** [comment]
Hey! Thank you for the PR and sorry for the delay, I will review this soon

**Comment by goxiaoy** [comment]
@greymag any updates?

**Review by greymag — APPROVED** [review]

**Pull request merged**
